# General site information
title: Creator Assets
baseurl: https://creatorassets.com
description: Copyright-free assets for all creators to use in any project. Feel free to use our assets in any video, movie, game, or other project without crediting.